version: "3.3"

services: 
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: connecting-best-age
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres